version: 1
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  file_handler:
    class: logging.FileHandler
    formatter: simple
    filename: logs/mylog.log

loggers:
  file_logger:
    level: DEBUG
    handlers: [file_handler]
